### ISSUE TITLE
differences  with kafka-run-class.sh kafka.tools.EndToEndLatency 

### ISSUE THREAD

**Issue by pgibert** [hey-johnnypark/kafka-latency-meter#1]
Thxa lot  for sharing
Please what is the main difference with the 
kafka-run-class.sh kafka.tools.EndToEndLatency 
**kafka.tools.EndToEndLatency$** broker_list topic num_messages producer_acks message_size_bytes [optional] properties_file  command 
from the kafka  bin delivery 

BR
phil

**Comment by hey-johnnypark** [comment]
Hi Phil,

there are not much differences. The motivation for the project is fun ;) 

However when you compare the output you get a bit more of insights. 

kafka-run-class kafka.tools.EndToEndLatency localhost:9092 test123 10000 all 1000
0	121.71780199999999
1000	1.145809
2000	1.2541110000000002
3000	1.060397
4000	1.280458
5000	1.1410820000000002
6000	1.174051
7000	1.376191
8000	1.168865
9000	1.036977
Avg latency: 1.2532 ms

AND

 johnnypark@starshooter  ~/tmp  java -jar kafka-latency-meter.jar --kafka.topic=test123 --spring.kafka.bootstrap-servers=localhost:9092 --kafka.messageSize=1000 --kafka.numMessages=10000
==============================================================

-- Timers ----------------------------------------------------------------------
roundtrip-latency-topic[test123]
             count = 9767
         mean rate = 500.50 calls/second
     1-minute rate = 502.54 calls/second
     5-minute rate = 502.90 calls/second
    15-minute rate = 502.97 calls/second
               min = 0.00 milliseconds
               max = 16.00 milliseconds
              mean = 1.08 milliseconds
            stddev = 0.62 milliseconds
            median = 1.00 milliseconds
              75% <= 1.00 milliseconds
              95% <= 2.00 milliseconds
              98% <= 2.00 milliseconds
              99% <= 2.00 milliseconds
            99.9% <= 4.00 milliseconds
